# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Welfare and Spending Effects of Consumption Stimulus Policies
email: ccarroll@jhu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Using a heterogeneous agent model calibrated to match measured spending dynamics
  over four years following an income shock (Fagereng, Holm, and Natvik (2021)),
  we assess the eﬀectiveness of three ﬁscal stimulus policies employed during recent
  recessions. Unemployment insurance (UI) extensions are the clear “bang for the buck”
  winner, especially when eﬀectiveness is measured in utility terms. Stimulus checks are
  second best and have the advantage (over UI) of being scalable to any desired size. A
  temporary (two-year) cut in the rate of wage taxation is considerably less eﬀective than
  the other policies and has negligible eﬀects in the version of our model without a
  multiplier.
baseurl: '/docs' # the subpath of your site, e.g. /blog
url: https://llorracc.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
